title: "Ranking języków programowania"
description: "Lista najpopularniejszych języków programowania z opisami i obrazkami."
theme: minima  # Możesz użyć innego motywu
author: "Adam Jasiński"
baseurl: "" # Jeśli publikujesz na GitHub Pages, zostaw puste
url: "https://adam-jasinski.github.io/my_jekyll_site" # Podmień na swój adres

# Ustawienia dla postów
permalink: /:title/

